-- AlterTable
ALTER TABLE "Education" ALTER COLUMN "yearFrom" SET DATA TYPE TEXT,
ALTER COLUMN "yearTo" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Experience" ALTER COLUMN "yearFrom" SET DATA TYPE TEXT,
ALTER COLUMN "yearTo" SET DATA TYPE TEXT;
